on:
  push:
    branches:
      - main
name: build gatsby
jobs:
  build_gatsby:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: yarn install
        run: yarn install

      - name: gatsby clean
        run: yarn clean

      - name: gatsby build
        env:
          GH_API_KEY: ${{ secrets.BLOG_KEY }}
        run: yarn build

      - name: deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.BLOG_KEY }}
          BUILD_DIR: './public'
